name: production
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: merge
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git pull origin
          git checkout prod
          git merge staging --allow-unrelated-histories
          git push origin prod
